const CANVAS_ID = 'mainField',
    ROAD_RADIUS = 150,
    LINE_ROAD_FREQ = 1,
    LINE_ROAD_ID = 1,
    CIRCLE_ROAD_FREQ = 1,
    CIRCLE_ROAD_ID = 2,
    EPS = 2,
    DIR_EPS = 0.5,
    DIST_BETWEEN_LINES = 20,
    LINE_WIDTH = 10,
    MAX_CARS_NUM = 10,
    POINTS_COMP_EPS = 1,
    MIN_NEAREST_POINTS_EPS = 5,
    MAX_NEAREST_POINTS_EPS = 10,
    FRAMES_DELAY = 5,
    FINISH_BORDERS_OFFSET = 5,
    MIN_DIST = 70,
    ALPHA_DIRECTION = -1,
    SPEED_INC = 0.5,
    SPEED_DEC = 1,
    LEAVE_MODE_SWITCHER_LABEL = {
        false: "уезжать с круга",
        true: "оставаться на кругу"
    };
